<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">

  <name>mrs_uav_diagnostics_sensors</name>
  <version>2.0.0</version>
  <description>Concrete DiagnosticsSensorHandler plugin implementations (GNSS, camera, generic,
    magnetometer, remote controller) for mrs_uav_managers's DiagnosticsManager.</description>

  <maintainer email="spurny@fly4future.com">Vojtech Spurny</maintainer>
  <maintainer email="rivera@fly4future.com">Marlon Rivera</maintainer>

  <license>MIT</license>

  <author email="spurny@fly4future.com">Vojtech Spurny</author>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_ros</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclpy</depend>
  <depend>rclcpp_components</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>pluginlib</depend>
  <depend>builtin_interfaces</depend>
  <depend>diagnostic_msgs</depend>
  <depend>mrs_msgs</depend>
  <depend>mrs_lib</depend>
  <depend>mrs_uav_managers</depend>
  <depend>nav_msgs</depend>
  <depend>nlohmann-json-dev</depend>
  <depend>ament_index_cpp</depend>

  <!-- Linters -->
  <test_depend>ament_cmake_clang_format</test_depend>
  <test_depend>ament_cmake_xmllint</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
